language: objective-c
env:
  global:
  - MODULE_NAME=ti.styledlabel
before_install:
- openssl aes-256-cbc -K $encrypted_9e0b5c87ddd9_key -iv $encrypted_9e0b5c87ddd9_iv
  -in token.txt.enc -out token.txt -d
- MODULE_ROOT=$PWD
script:
- echo "Hello"
after_success:
- source deploy.sh
